language: ruby
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - binutils-dev
    - g++-4.7

rvm:
 - 2.0
 - 2.1
 - 2.2
 - 2.3.0

matrix:
  exclude:
    - os: osx
  include:
    - os: linux
      rvm: 2.0
      env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_MPC="yes" RUBOCOP="yes"
    - os: linux
      rvm: 2.3.0
      env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_MPC="yes"
    - os: linux
      rvm: 2.3.0
      env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_MPFR="yes"
    - os: osx
      rvm: 2.0
  allow_failures:
    - os: osx
      rvm: 2.0

install:
  - export RUBY_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - git config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
  - git fetch origin
  - git checkout `cat ../symengine_version.txt`

  # Setup travis for C++ library
  - source bin/install_travis.sh

  # Build C++ library
  - bin/test_travis.sh

  # Setup travis for Ruby wrappers
  - cd $RUBY_SOURCE_DIR
  - bundle install

script:
  # Build ruby gem
  - gem build symengine.gemspec
  # Convert all warnings to errors
  - export CFLAGS="-Werror"
  # Install ruby gem
  - gem install symengine-0.1.0.gem --install-dir $HOME --verbose -- -DSymEngine_DIR=$our_install_dir
  # Check for code style using rubocop
  - if [[ "${RUBOCOP}" == "yes" ]]; then rubocop; fi

  # Test ruby gem
  - gem install gem-path --no-ri --no-rdoc
  - cd $HOME/gems/symengine-0.1.0/
  - bundle exec rspec

notifications:
  email: false
